[tool.ruff]
# Code quality + import sorting + formatter
line-length = 100
target-version = "py310"

# Do NOT check .ipynb files
extend-exclude = [
    "**/*.ipynb"
]

# Enable important lint rules (safe for your project)
lint.select = [
    "E",   # Pyflakes & style errors
    "F",   # Pyflakes
    "W",   # Warnings
    "I",   # Import sorting
]

[tool.ruff.format]
# Use Ruff as the formatter
quote-style = "double"
indent-style = "space"
line-ending = "auto"
